[pytest]
testpaths = test
python_files = *test*.py
python_classes = *Test*
python_functions = *test*
--import-mode=importlib


# Опции командной строки по умолчанию
# -q : тихий режим (меньше вывода)
# --alluredir=allure-files : директория для хранения результатов тестов (для Allure)
# --import-mode=importlib : ключевая опция для решения проблем с импортом
addopts = -q --alluredir=allure-files --import-mode=importlib