[ui]
base_url=https://ru.yougile.com
timeout=4
# для выбора браузера
browser_name=chrome

[api]
base_url=https://ru.yougile.com/api-v2
token=5zO0PQDcT4kSEHsPEzvwtu230DpmLM8VD7BaawTil7QEfToMhBur2Az7SCKPM8go

